[2025-08-20T15:26:12.712+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-20T15:26:12.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation_dag.run_data_transformation scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T15:26:12.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation_dag.run_data_transformation scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T15:26:12.742+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-20T15:26:12.774+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_transformation> on 2025-08-19 00:00:00+00:00
[2025-08-20T15:26:12.780+0000] {standard_task_runner.py:63} INFO - Started process 20394 to run task
[2025-08-20T15:26:12.784+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_transformation_dag', 'run_data_transformation', 'scheduled__2025-08-19T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpr4wo9win']
[2025-08-20T15:26:12.786+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask run_data_transformation
[2025-08-20T15:26:12.857+0000] {task_command.py:426} INFO - Running <TaskInstance: data_transformation_dag.run_data_transformation scheduled__2025-08-19T00:00:00+00:00 [running]> on host 4e81cb17b5ff
[2025-08-20T15:26:12.961+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_transformation_dag' AIRFLOW_CTX_TASK_ID='run_data_transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T00:00:00+00:00'
[2025-08-20T15:26:12.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-20T15:26:12.969+0000] {transformation_dag.py:18} INFO - Running data processing tasks for scheduled__2025-08-19T00:00:00+00:00
[2025-08-20T15:26:12.969+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-20T15:26:12.969+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/airflow/dags/transformation_dag.py", line 20, in _run_data_processing
    fuzzy_match_results = calculate_fuzzy_match()
TypeError: calculate_fuzzy_match() missing 2 required positional arguments: 'target_string' and 'candidate_list_of_strings'
[2025-08-20T15:26:12.983+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_transformation_dag, task_id=run_data_transformation, run_id=scheduled__2025-08-19T00:00:00+00:00, execution_date=20250819T000000, start_date=20250820T152612, end_date=20250820T152612
[2025-08-20T15:26:13.076+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task run_data_transformation (calculate_fuzzy_match() missing 2 required positional arguments: 'target_string' and 'candidate_list_of_strings'; 20394)
[2025-08-20T15:26:13.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-20T15:26:13.132+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-20T15:26:13.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
